In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure

In [2]:
df = pd.read_csv("viajes.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1828 entries, 0 to 1827
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   timestamp            1828 non-null   int64
 1   universidad          1828 non-null   object
 2   comuna_origen        1828 non-null   object
 3   tipo_de_viaje        1828 non-null   int64
 4   tipo_de_universidad  1828 non-null   int64
 5   tiene_residencia     1828 non-null   int64
 6   count                1828 non-null   int64
 7   tamaño_uni           1828 non-null   int64
 8   n_carreras           1828 non-null   int64
dtypes: int64(7), object(2)
memory usage: 128.7+ KB

In [3]:
def one_hot_encoder(dataframe, categorical_cols, drop_first=True):
    dataframe = pd.get_dummies(dataframe, columns = categorical_cols, drop_first=drop_first)
    return dataframe

In [4]:

df_final = one_hot_encoder(df, ['universidad'])
df_final

,timestamp,comuna_origen,tipo_de_viaje,tipo_de_universidad,tiene_residencia,count,tamaño_uni,n_carreras,universidad_Campus Beauchef Uchile,universidad_Campus Oriente UC,universidad_Campus Sur Uchile Uchile,universidad_Casa central UC,universidad_Casa central Uchile,universidad_El comendador UC,universidad_Juan Gómez Millas Uchile,universidad_North CampuS (Dra. Eloisa Diaz) Uchile,universidad_San Joaquín UC,universidad_UDD Sede Santiago,universidad_UDP Facultad de economía y empresas
0,0,Conchalí,0,0,1,1,45000,53,0,0,0,0,0,0,0,0,0,0,0
1,0,Huechuraba,0,0,1,1,45000,53,0,0,0,0,0,0,0,0,0,0,0
2,0,Lo Espejo,0,0,1,1,45000,53,0,0,0,0,0,0,0,0,0,0,0
3,0,Providencia,0,0,1,7,45000,53,0,0,0,0,0,0,0,0,0,0,0
4,0,Quilicura,0,0,1,1,45000,53,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1823,23,Colina,0,1,0,1,26400,14,0,0,0,0,0,0,0,0,0,0,1
1824,23,Huechuraba,0,1,0,4,26400,14,0,0,0,0,0,0,0,0,0,0,1
1825,23,Huechuraba,1,1,0,9,26400,14,0,0,0,0,0,0,0,0,0,0,1
1826,23,Las Condes,0,1,0,1,26400,14,0,0,0,0,0,0,0,0,0,0,1
1827,23,Recoleta,0,1,0,10,26400,14,0,0,0,0,0,0,0,0,0,0,1

In [5]:
df_final = one_hot_encoder(df, ['comuna_origen', 'universidad'])
df_final

,timestamp,tipo_de_viaje,tipo_de_universidad,tiene_residencia,count,tamaño_uni,n_carreras,comuna_origen_Calera de Tango,comuna_origen_Cerrillos,comuna_origen_Cerro Navia,...,universidad_Campus Oriente UC,universidad_Campus Sur Uchile Uchile,universidad_Casa central UC,universidad_Casa central Uchile,universidad_El comendador UC,universidad_Juan Gómez Millas Uchile,universidad_North CampuS (Dra. Eloisa Diaz) Uchile,universidad_San Joaquín UC,universidad_UDD Sede Santiago,universidad_UDP Facultad de economía y empresas
0,0,0,0,1,1,45000,53,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,1,45000,53,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,1,45000,53,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,7,45000,53,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,1,1,45000,53,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1823,23,0,1,0,1,26400,14,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1824,23,0,1,0,4,26400,14,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1825,23,1,1,0,9,26400,14,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1826,23,0,1,0,1,26400,14,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1827,23,0,1,0,10,26400,14,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [6]:
X = df_final.drop(['count'], axis=1, inplace=False)
y = df_final['count']

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [8]:
from sklearn.ensemble import ExtraTreesRegressor

In [9]:
model = ExtraTreesRegressor(max_features=40)

In [10]:
grid_result = model.fit(X_train, y_train)

In [11]:
print('Model name', model)
from sklearn import metrics
y_pred = model.predict(X_test)
print('Mean Absolute Error (MAE): ', round(metrics.mean_absolute_error(y_test, y_pred), 3))
print('Mean Squared Error (MSE): ', round(metrics.mean_squared_error(y_test, y_pred), 3))
print('Root Mean Squared Error (RMSE): ', round(np.sqrt(metrics.mean_squared_error(y_test, y_pred)), 3))
print('R2 Score: ', round(metrics.r2_score(y_test, y_pred), 5))

def MAPE(y_test, y_pred):
    y_test, y_pred = np.array(y_test), np.array(y_pred)
    return np.mean(np.abs((y_test - y_pred) / y_test)) * 100
    
    # Evaluation of MAPE
result = MAPE(y_test, y_pred)
print('Mean Absolute Percentage Error (MAPE): ', round(result, 2), '%')

Model name ExtraTreesRegressor(max_features=40)
Mean Absolute Error (MAE):  1.796
Mean Squared Error (MSE):  15.141
Root Mean Squared Error (RMSE):  3.891
R2 Score:  0.76329
Mean Absolute Percentage Error (MAPE):  52.97 %

In [12]:
var = df_final.iloc[1824:1825]
print(var['count'])
var = var.drop('count',axis=1)
var

1824    4
Name: count, dtype: int64

,timestamp,tipo_de_viaje,tipo_de_universidad,tiene_residencia,tamaño_uni,n_carreras,comuna_origen_Calera de Tango,comuna_origen_Cerrillos,comuna_origen_Cerro Navia,comuna_origen_Colina,...,universidad_Campus Oriente UC,universidad_Campus Sur Uchile Uchile,universidad_Casa central UC,universidad_Casa central Uchile,universidad_El comendador UC,universidad_Juan Gómez Millas Uchile,universidad_North CampuS (Dra. Eloisa Diaz) Uchile,universidad_San Joaquín UC,universidad_UDD Sede Santiago,universidad_UDP Facultad de economía y empresas
1824,23,0,1,0,26400,14,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [13]:
result = model.predict(var.to_numpy())
result

c:\Users\maria\anaconda3\envs\dl\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but ExtraTreesRegressor was fitted with feature names
  warnings.warn(

array([4.])

In [14]:
var = df_final.iloc[3:4]
print(var['count'])
var = var.drop('count',axis=1)
var

3    7
Name: count, dtype: int64

,timestamp,tipo_de_viaje,tipo_de_universidad,tiene_residencia,tamaño_uni,n_carreras,comuna_origen_Calera de Tango,comuna_origen_Cerrillos,comuna_origen_Cerro Navia,comuna_origen_Colina,...,universidad_Campus Oriente UC,universidad_Campus Sur Uchile Uchile,universidad_Casa central UC,universidad_Casa central Uchile,universidad_El comendador UC,universidad_Juan Gómez Millas Uchile,universidad_North CampuS (Dra. Eloisa Diaz) Uchile,universidad_San Joaquín UC,universidad_UDD Sede Santiago,universidad_UDP Facultad de economía y empresas
3,0,0,0,1,45000,53,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
result = model.predict(var.to_numpy())
result

c:\Users\maria\anaconda3\envs\dl\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but ExtraTreesRegressor was fitted with feature names
  warnings.warn(

array([7.])